export interface ComicMangaItem {
  id: number;
  nombre: string;
  descripcion: string;
  autor: string;
  genero: string;
  tipo: string;
  estado: string;
  fecha_de_publicacion: string;
  imagen_url: string;
  categoria: string;
}

export const mock: ComicMangaItem[] = [
  {
    id: 1,
    nombre: "Batman: Year One",
    descripcion: "La historia del primer año de Bruce Wayne como Batman.",
    autor: "Frank Miller",
    genero: "Acción, Crimen, Drama",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "1987-02-01",
    imagen_url: "/img/batmanYearOne.png",
    categoria: "DC",
  },
  {
    id: 2,
    nombre: "Superman: Red Son",
    descripcion: "¿Y si Superman hubiera aterrizado en la Unión Soviética?",
    autor: "Mark Millar",
    genero: "Ficción alternativa, Superhéroes",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2003-04-01",
    imagen_url: "/img/supermanRedSon.png",
    categoria: "DC",
  },
  {
    id: 3,
    nombre: "The Flash: Rebirth",
    descripcion: "Barry Allen regresa después de su muerte en Crisis.",
    autor: "Geoff Johns",
    genero: "Acción, Superhéroes",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2009-04-01",
    imagen_url: "/img/flashRebirth.png",
    categoria: "DC",
  },
  {
    id: 4,
    nombre: "Wonder Woman: Earth One",
    descripcion: "Una nueva mirada moderna a los orígenes de Wonder Woman.",
    autor: "Grant Morrison",
    genero: "Superhéroes, Fantasía",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2016-04-12",
    imagen_url: "/img/wwEarthOne.png",
    categoria: "DC",
  },
  {
    id: 5,
    nombre: "Green Lantern: Secret Origin",
    descripcion: "Los inicios de Hal Jordan como Linterna Verde.",
    autor: "Geoff Johns",
    genero: "Ciencia ficción, Acción",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2008-07-01",
    imagen_url: "/img/glSecretOrigin.png",
    categoria: "DC",
  },
  {
    id: 6,
    nombre: "Aquaman: The Trench",
    descripcion: "Aquaman debe enfrentar criaturas de las profundidades.",
    autor: "Geoff Johns",
    genero: "Acción, Aventura",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2011-09-28",
    imagen_url: "/img/aquamanTheTrench.png",
    categoria: "DC",
  },
  {
    id: 7,
    nombre: "Justice League: Origin",
    descripcion: "La formación de la Liga de la Justicia moderna.",
    autor: "Geoff Johns",
    genero: "Acción, Superhéroes",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2011-10-01",
    imagen_url: "/img/jLOrigin.png",
    categoria: "DC",
  },
  {
    id: 8,
    nombre: "Batgirl: Year One",
    descripcion: "Barbara Gordon comienza su carrera como Batgirl.",
    autor: "Scott Beatty",
    genero: "Superhéroes, Aventura",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2003-01-01",
    imagen_url: "/img/batgirlYearOne.png",
    categoria: "DC",
  },
  {
    id: 9,
    nombre: "Nightwing: Year One",
    descripcion:
      "Dick Grayson deja de ser Robin para convertirse en Nightwing.",
    autor: "Chuck Dixon",
    genero: "Acción, Superhéroes",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2005-01-01",
    imagen_url: "/img/nigthwingYearOne.png",
    categoria: "DC",
  },
  {
    id: 10,
    nombre: "The Killing Joke",
    descripcion:
      "Una historia oscura que explora la relación entre Batman y el Joker.",
    autor: "Alan Moore",
    genero: "Crimen, Drama, Psicológico",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "1988-03-29",
    imagen_url: "/img/killingJoke.png",
    categoria: "DC",
  },
  {
    id: 11,
    nombre: "Spider-Man: Blue",
    descripcion: "Peter Parker recuerda sus primeros días como Spider-Man.",
    autor: "Jeph Loeb",
    genero: "Superhéroes, Romance",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2002-07-01",
    imagen_url: "/img/spideyBlue.png",
    categoria: "Marvel",
  },
  {
    id: 12,
    nombre: "Iron Man: Extremis",
    descripcion: "Tony Stark enfrenta una amenaza que cambia su mundo.",
    autor: "Warren Ellis",
    genero: "Acción, Ciencia ficción",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2005-01-01",
    imagen_url: "/img/ironManExtremis.png",
    categoria: "Marvel",
  },
  {
    id: 13,
    nombre: "Thor: God of Thunder",
    descripcion: "Thor lucha contra Gorr, el carnicero de dioses.",
    autor: "Jason Aaron",
    genero: "Fantasía, Mitología",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2012-11-01",
    imagen_url: "/img/thorGodThunder.png",
    categoria: "Marvel",
  },
  {
    id: 14,
    nombre: "Captain America: Winter Soldier",
    descripcion:
      "El Capitán América descubre que Bucky ha vuelto como asesino.",
    autor: "Ed Brubaker",
    genero: "Acción, Espionaje",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2005-01-01",
    imagen_url: "/img/winterSoldier.png",
    categoria: "Marvel",
  },
  {
    id: 15,
    nombre: "Hawkeye: My Life as a Weapon",
    descripcion: "Las aventuras de Clint Barton fuera de los Vengadores.",
    autor: "Matt Fraction",
    genero: "Acción, Comedia",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2012-08-01",
    imagen_url: "/img/hawkeye.png",
    categoria: "Marvel",
  },
  {
    id: 16,
    nombre: "Black Panther: A Nation Under Our Feet",
    descripcion: "T'Challa enfrenta amenazas internas en Wakanda.",
    autor: "Ta-Nehisi Coates",
    genero: "Política, Acción",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2016-04-01",
    imagen_url: "/img/blackPanter.png",
    categoria: "Marvel",
  },
  {
    id: 17,
    nombre: "Doctor Strange: The Oath",
    descripcion:
      "Doctor Strange investiga un complot que pone en riesgo su vida.",
    autor: "Brian K. Vaughan",
    genero: "Magia, Misterio",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2006-10-01",
    imagen_url: "/img/strange.png",
    categoria: "Marvel",
  },
  {
    id: 18,
    nombre: "Daredevil: Born Again",
    descripcion: "El Reypin destruye la vida de Matt Murdock.",
    autor: "Frank Miller",
    genero: "Crimen, Acción",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "1986-02-01",
    imagen_url: "/img/daredevil.png",
    categoria: "Marvel",
  },
  {
    id: 19,
    nombre: "Wolverine: Old Man Logan",
    descripcion: "Un Logan viejo en un futuro distópico.",
    autor: "Mark Millar",
    genero: "Post-apocalíptico, Acción",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "2008-06-01",
    imagen_url: "/img/wolverine.png",
    categoria: "Marvel",
  },
  {
    id: 20,
    nombre: "X-Men: Days of Future Past",
    descripcion: "Viajes en el tiempo para evitar un futuro catastrófico.",
    autor: "Chris Claremont",
    genero: "Ciencia ficción, Acción",
    tipo: "Comic",
    estado: "Finalizado",
    fecha_de_publicacion: "1981-01-01",
    imagen_url: "/img/xmen.png",
    categoria: "Marvel",
  },
  {
    id: 21,
    nombre: "One Piece",
    descripcion:
      "Luffy y su tripulación buscan el tesoro legendario conocido como One Piece.",
    autor: "Eiichiro Oda",
    genero: "Aventura, Acción, Fantasía",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "1997-07-22",
    imagen_url: "/img/onePiece.png",
    categoria: "Shonen",
  },
  {
    id: 22,
    nombre: "Naruto",
    descripcion: "Un joven ninja busca ser el mejor y proteger su aldea.",
    autor: "Masashi Kishimoto",
    genero: "Acción, Aventura, Comedia",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "1999-09-21",
    imagen_url: "/img/naruto.png",
    categoria: "Shonen",
  },
  {
    id: 23,
    nombre: "Bleach",
    descripcion:
      "Ichigo obtiene poderes de Shinigami y combate espíritus malignos.",
    autor: "Tite Kubo",
    genero: "Acción, Sobrenatural",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "2001-08-07",
    imagen_url: "/img/bleach.png",
    categoria: "Shonen",
  },
  {
    id: 24,
    nombre: "Dragon Ball",
    descripcion:
      "Las aventuras de Goku desde su niñez hasta convertirse en héroe mundial.",
    autor: "Akira Toriyama",
    genero: "Acción, Aventura, Artes marciales",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "1984-12-03",
    imagen_url: "/img/dragonBall.png",
    categoria: "Shonen",
  },
  {
    id: 25,
    nombre: "My Hero Academia",
    descripcion:
      "Izuku Midoriya quiere convertirse en el mayor héroe de todos.",
    autor: "Kohei Horikoshi",
    genero: "Acción, Superhéroes, Escuela",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2014-07-07",
    imagen_url: "/img/mha.png",
    categoria: "Shonen",
  },
  {
    id: 26,
    nombre: "Attack on Titan",
    descripcion:
      "La humanidad lucha por sobrevivir contra gigantes devoradores.",
    autor: "Hajime Isayama",
    genero: "Acción, Drama, Misterio",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "2009-09-09",
    imagen_url: "/img/snk.png",
    categoria: "Shonen",
  },
  {
    id: 27,
    nombre: "Demon Slayer",
    descripcion:
      "Un joven busca venganza contra los demonios que mataron a su familia.",
    autor: "Koyoharu Gotouge",
    genero: "Acción, Sobrenatural, Drama",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "2016-02-15",
    imagen_url: "/img/kny.png",
    categoria: "Shonen",
  },
  {
    id: 28,
    nombre: "Jujutsu Kaisen",
    descripcion:
      "Yuji Itadori se convierte en hechicero para combatir maldiciones.",
    autor: "Gege Akutami",
    genero: "Acción, Sobrenatural, Horror",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2018-03-05",
    imagen_url: "/img/jjk.png",
    categoria: "Shonen",
  },
  {
    id: 29,
    nombre: "Black Clover",
    descripcion:
      "Asta quiere convertirse en el Rey Mago a pesar de no tener magia.",
    autor: "Yūki Tabata",
    genero: "Fantasía, Acción, Magia",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2015-02-16",
    imagen_url: "/img/blackClover.png",
    categoria: "Shonen",
  },
  {
    id: 30,
    nombre: "Hunter x Hunter",
    descripcion:
      "Gon Freecss busca a su padre y se convierte en cazador profesional.",
    autor: "Yoshihiro Togashi",
    genero: "Aventura, Acción, Fantasía",
    tipo: "Manga",
    estado: "Hiato",
    fecha_de_publicacion: "1998-03-16",
    imagen_url: "/img/hxh.png",
    categoria: "Shonen",
  },
  {
    id: 31,
    nombre: "Re:Zero - Starting Life in Another World",
    descripcion:
      "Subaru Natsuki es transportado a otro mundo y revive el mismo día al morir.",
    autor: "Tappei Nagatsuki",
    genero: "Fantasía, Drama, Suspenso",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2014-06-27",
    imagen_url: "/img/reZero.png",
    categoria: "Isekai",
  },
  {
    id: 32,
    nombre: "That Time I Got Reincarnated as a Slime",
    descripcion:
      "Un hombre muere y renace como un slime con habilidades únicas.",
    autor: "Fuse",
    genero: "Fantasía, Aventura, Acción",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2015-03-26",
    imagen_url: "/img/ttigras.png",
    categoria: "Isekai",
  },
  {
    id: 33,
    nombre: "No Game No Life",
    descripcion:
      "Dos hermanos expertos en videojuegos son transportados a un mundo donde todo se resuelve con juegos.",
    autor: "Yuu Kamiya",
    genero: "Fantasía, Estrategia, Aventura",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2013-01-27",
    imagen_url: "/img/noGame.png",
    categoria: "Isekai",
  },
  {
    id: 34,
    nombre: "The Rising of the Shield Hero",
    descripcion:
      "Naofumi es invocado a otro mundo como el Héroe del Escudo y enfrentado al desprecio de todos.",
    autor: "Aneko Yusagi",
    genero: "Fantasía, Aventura, Acción",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2014-08-22",
    imagen_url: "/img/rsh.png",
    categoria: "Isekai",
  },
  {
    id: 35,
    nombre: "Overlord",
    descripcion:
      "Un jugador queda atrapado en el mundo de su videojuego favorito como un poderoso lich.",
    autor: "Kugane Maruyama",
    genero: "Fantasía oscura, Acción",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "2014-11-26",
    imagen_url: "/img/overlord.png",
    categoria: "Isekai",
  },
  {
    id: 36,
    nombre: "Berserk",
    descripcion:
      "La historia del guerrero Guts y su lucha contra demonios y el destino.",
    autor: "Kentaro Miura",
    genero: "Fantasía oscura, Acción, Drama",
    tipo: "Manga",
    estado: "En emisión",
    fecha_de_publicacion: "1989-08-25",
    imagen_url: "/img/berserk.png",
    categoria: "Seinen",
  },
  {
    id: 37,
    nombre: "Monster",
    descripcion:
      "Un neurocirujano japonés en Alemania se ve involucrado en una red de asesinatos tras salvar a un niño.",
    autor: "Naoki Urasawa",
    genero: "Suspenso, Crimen, Psicológico",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "1994-12-05",
    imagen_url: "/img/monster.png",
    categoria: "Seinen",
  },
  {
    id: 38,
    nombre: "Vagabond",
    descripcion:
      "Una dramatización de la vida del legendario espadachín Miyamoto Musashi.",
    autor: "Takehiko Inoue",
    genero: "Histórico, Acción, Drama",
    tipo: "Manga",
    estado: "Hiato",
    fecha_de_publicacion: "1998-03-23",
    imagen_url: "/img/vagabound.png",
    categoria: "Seinen",
  },
  {
    id: 39,
    nombre: "Tokyo Ghoul",
    descripcion:
      "Un joven se convierte en mitad ghoul tras un accidente y debe aprender a sobrevivir.",
    autor: "Sui Ishida",
    genero: "Horror, Acción, Drama",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "2011-09-08",
    imagen_url: "/img/tokyoGhoul.png",
    categoria: "Seinen",
  },
  {
    id: 40,
    nombre: "20th Century Boys",
    descripcion:
      "Un grupo de amigos intenta detener una amenaza que predijeron en su infancia.",
    autor: "Naoki Urasawa",
    genero: "Misterio, Drama, Ciencia ficción",
    tipo: "Manga",
    estado: "Finalizado",
    fecha_de_publicacion: "1999-01-20",
    imagen_url: "/img/20cb.png",
    categoria: "Seinen",
  },
];

export const obtenerMangasAleatorios = () => {
  const mangas = mock.filter(
    item =>
      item.categoria === "Shonen" ||
      item.categoria === "Isekai" ||
      item.categoria === "Seinen"
  );
  return mangas.sort(() => 0.5 - Math.random()).slice(0, 10);
};

export const obtenerComicsAleatorios = () => {
  const comics = mock.filter(
    item => item.categoria === "Marvel" || item.categoria === "DC"
  );
  return comics.sort(() => 0.5 - Math.random()).slice(0, 10);
};
